# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('schedule', '0001_squashed_0004_auto_20150807_0754'), ('schedule', '0002_remove_broadcast_ending'), ('schedule', '0003_auto_20150918_1019')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Asteko eguna')),
                ('beginning', models.TimeField(verbose_name='Hasiera')),
                ('name', models.CharField(max_length=64, verbose_name='Izena')),
                ('classification', models.CharField(blank=True, max_length=512, verbose_name='Classification')),
                ('link', models.CharField(blank=True, help_text='Esteka lokala bada, ez jarri haren protokoloa eta domeinua: erabili/helbideren/bat https://domain.tld/helbideren/bat beharrean', max_length=256, verbose_name='Esteka')),
            ],
            options={
                'ordering': ['weekday'],
                'verbose_name': 'Saioa',
                'verbose_name_plural': 'Saioak',
            },
        ),
    ]
