# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('schedule', '0001_squashed_0004_auto_20150807_0754'), ('schedule', '0002_remove_broadcast_ending'), ('schedule', '0003_auto_20150918_1019')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Weekday')),
                ('beginning', models.TimeField(verbose_name='Beginning')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('classification', models.CharField(blank=True, max_length=512, verbose_name='Classification')),
                ('link', models.CharField(blank=True, help_text='If the link is local, do not prepend the schema and the domain: use /some/path instead of https://domain.tld/some/path', max_length=256, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcasts',
                'ordering': ['weekday'],
            },
        ),
    ]
