site_name: Antxetamedia
theme: readthedocs
pages:
    - Ongietorri: index.md
    - Erabiltzaileak: users/index.md
    - Developers:
        - Setup: devs/index.md
        - Requirements: devs/requirements.md
        - Architecture: devs/architecture.md
