site_name: Antxetamedia
theme: readthedocs
pages:
    - Ongietorri: index.md
    - Erabiltzaileak: users/index.md
    - Garatzaileak:
        - Setup: devs/index.md
        - Description: devs/description.md
        - Architecture: devs/architecture.md
