# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 19:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('flatpages', '0001_initial'), ('flatpages', '0002_auto_20150709_1208'), ('flatpages', '0003_auto_20150729_1835')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flatpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_menu', models.BooleanField(default=False, verbose_name='Menuan')),
                ('name', models.CharField(max_length=128, verbose_name='Izena')),
                ('path', models.SlugField(help_text='/f/zure_helbidea helbidean egongo da eskuragarri', max_length=128, unique=True, verbose_name='Helbidea')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Edukia')),
            ],
            options={
                'verbose_name': 'Orri laua',
                'verbose_name_plural': 'Orri lauak',
            },
        ),
    ]
