# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 00:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('widgets', '0001_initial'), ('widgets', '0002_auto_20150729_1835')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Izena')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Kokapena')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Edukia')),
            ],
            options={
                'verbose_name_plural': 'Widgetak',
                'ordering': ['position'],
                'verbose_name': 'Widgeta',
            },
        ),
    ]
