# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 18:46
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_reseted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(verbose_name='Recurrences'),
        ),
    ]
