# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 23:58
from __future__ import unicode_literals

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_auto_20150619_1321'), ('projects', '0003_auto_20150625_1205'), ('projects', '0004_remove_projectshow_featured'), ('projects', '0005_auto_20150722_1429'), ('projects', '0006_auto_20150729_1835'), ('projects', '0007_auto_20150729_2015'), ('projects', '0008_auto_20150729_2214'), ('projects', '0009_auto_20150807_0733'), ('projects', '0010_auto_20150819_1031')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPodcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Izenburua')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('show',), verbose_name='Helbide izena')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Deskribapena')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Argitarapen data')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='shows', verbose_name='Irudia')),
            ],
            options={
                'verbose_name': 'Project podcast',
                'ordering': ['-pub_date'],
                'verbose_name_plural': 'Project podcasts',
            },
        ),
        migrations.CreateModel(
            name='ProjectProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Izena')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='Helbide izena')),
            ],
            options={
                'verbose_name': 'Project producer',
                'verbose_name_plural': 'Project producers',
            },
        ),
        migrations.CreateModel(
            name='ProjectShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Izena')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='Helbide izena')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Deskribapena')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='shows', verbose_name='Irudia')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, help_text='Only the year is taken into account', verbose_name='Creation date')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectProducer', verbose_name='Producer')),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['-creation_date'],
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='projectpodcast',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectShow', verbose_name='Show'),
        ),
    ]
