# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blobs', '0002_auto_20160111_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='license',
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
