# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blobs', '0004_auto_20160914_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='local',
            field=models.FileField(blank=True, help_text='If set, the file will be uploaded to the remote storage and the link will be set at the remote field.', max_length=512, null=True, upload_to='blobs', verbose_name='Local file'),
        ),
    ]
