# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 19:03
from __future__ import unicode_literals

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    replaces = [('radio', '0001_initial'), ('radio', '0002_auto_20150619_1321'), ('radio', '0003_auto_20150625_1205'), ('radio', '0004_auto_20150729_1835'), ('radio', '0005_auto_20150729_2015'), ('radio', '0006_auto_20150807_0733')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Radio categories',
                'verbose_name': 'Radio category',
            },
        ),
        migrations.CreateModel(
            name='RadioPodcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('show',), verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='shows', verbose_name='Image')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name_plural': 'Radio podcasts',
                'verbose_name': 'Radio podcast',
            },
        ),
        migrations.CreateModel(
            name='RadioProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Radio producers',
                'verbose_name': 'Radio producer',
            },
        ),
        migrations.CreateModel(
            name='RadioShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='shows', verbose_name='Image')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.RadioCategory', verbose_name='Category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.RadioProducer', verbose_name='Producer')),
            ],
            options={
                'verbose_name_plural': 'Radio shows',
                'verbose_name': 'Radio show',
            },
        ),
        migrations.AddField(
            model_name='radiopodcast',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.RadioShow', verbose_name='Show'),
        ),
    ]
