# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_reseted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioshow',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.RadioCategory', verbose_name='Category'),
        ),
    ]
