# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 23:52
from __future__ import unicode_literals

import antxetamedia.news.fields
import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    replaces = [('news', '0001_initial'), ('news', '0002_auto_20150618_2232'), ('news', '0003_auto_20150619_1321'), ('news', '0004_auto_20150625_1200'), ('news', '0005_auto_20150625_1205'), ('news', '0006_remove_newsshow_featured'), ('news', '0007_auto_20150712_1436'), ('news', '0008_auto_20150729_1835'), ('news', '0009_auto_20150729_2015'), ('news', '0010_auto_20150807_0733'), ('news', '0011_auto_20150915_0327'), ('news', '0012_add_featured_field')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Izena')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='Helbide izena')),
            ],
            options={
                'verbose_name': 'Berri saila',
                'verbose_name_plural': 'Berrien sailak',
            },
        ),
        migrations.CreateModel(
            name='NewsPodcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Izenburua')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('show',), verbose_name='Helbide izena')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Deskribapena')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Argitarapen data')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='shows', verbose_name='Irudia')),
                ('featured', antxetamedia.news.fields.UniqueTrueBooleanField(default=False, verbose_name='Nabarmendua')),
                ('categories', models.ManyToManyField(to='news.NewsCategory', verbose_name='Sailak')),
            ],
            options={
                'verbose_name': 'Berria',
                'ordering': ['-featured', '-pub_date'],
                'verbose_name_plural': 'Berriak',
            },
        ),
        migrations.CreateModel(
            name='NewsShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Izena')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='Helbide izena')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Deskribapena')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='shows', verbose_name='Irudia')),
            ],
            options={
                'verbose_name': 'Berrien ekoizlea',
                'verbose_name_plural': 'Berrien ekoizleak',
            },
        ),
        migrations.AddField(
            model_name='newspodcast',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsShow', verbose_name='Saioa'),
        ),
    ]
